on:
  schedule:
    - cron: '08 12 * * *'

jobs:
  check-tournaments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v7
        env:
          KEY: ${{ secrets.FIREBASE_KEY }}
          EMAIL: ${{ secrets.FIREBASE_EMAIL }}
          PASSW: ${{ secrets.FIREBASE_PASSW }}
        with:
          script: |
            import { initializeApp } from "firebase/app";
            import { getFirestore, setDoc, doc } from "firebase/firestore";
            import { getAuth, signInWithEmailAndPassword } from "firebase/auth";
            
            const firebaseConfig = {
              apiKey: process.env.KEY,
              authDomain: "skill-challenge-45a1d.firebaseapp.com",
              projectId: "skill-challenge-45a1d",
              storageBucket: "skill-challenge-45a1d.appspot.com",
              messagingSenderId: "232281189436",
              appId: "1:232281189436:web:2d278b4a895b458b93a739"
            };
            
            const app = initializeApp(firebaseConfig);
            
            const db = getFirestore(app);

            const auth = getAuth();

            signInWithEmailAndPassword(process.env.email, process.env.password, auth).then((resp)=>{
              setDoc(doc(db,"users",resp.uid),{});
            });
            
